- name: Run PostgreSQL container
  docker_container:
    name: database
    image: chaz01/tp-devops-database
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: my-network