- name: Run PostgreSQL container
  docker_container:
    name: "{{ db_container_name }}"
    image: chaz01/tp-devops-database
    pull: "{{ docker_pull }}"
    recreate: "{{ docker_recreate }}"
    force_kill: "{{ docker_force_kill }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    networks:
      - name: "{{ docker_network }}"
        aliases:
          - "{{ db_container_name }}"
