- name: Run HTTPD reverse proxy container
  docker_container:
    name: httpd
    image: chaz01/tp-devops-httpd:latest
    state: started
    restart_policy: always
    published_ports:
      - "8080:80"   
    networks:
      - name: my-network
