# group_vars/all.yml

# Containers names
db_container_name: database
api_container_name: simple-api
proxy_container_name: httpd

# Docker network
docker_network: my-network

# Docker settings communs
docker_pull: true
docker_recreate: true
docker_force_kill: true
docker_state: started
docker_restart_policy: always

# Interpreter
ansible_python_interpreter: /usr/bin/python3

# Database credentials
database_host: "{{ lookup('env', 'DATABASE_HOST') }}"
database_password: "{{ lookup('env', 'DATABASE_PASSWORD') }}"
postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"


# Port mapping for HTTPD proxy
proxy_port: "8080"
