
- name: Run simple-api container
  docker_container:
    name: simple-api
    image: chaz01/tp-devops-simple-api:latest
    state: started
    restart_policy: always
    env:
      DATABASE_HOST: database
      DATABASE_PASSWORD: pwd
    networks:
      - name: my-network