- name: Run simple-api container
  docker_container:
    name: "{{ api_container_name }}"
    image: chaz01/tp-devops-simple-api:latest
    pull: true
    recreate: true
    force_kill: true
    state: started
    restart_policy: always
    env:
      DATABASE_HOST: "{{ database_host }}"
      DATABASE_PASSWORD: "{{ database_password }}"
    networks:
      - name: "{{ docker_network }}"
        aliases:
          - "{{ api_container_name }}"
